"""Turn a PNG sprite sheet into vector sprites for runner-band.

The desktop app will not draw a PNG embedded in an Svg, so each sprite becomes
plain SVG paths: one run of same-colored pixels per row.

Usage: python3 sheet_to_svg.py sheet.png boxes.json out/sheet.ts [scale]
  boxes.json maps each sprite name to [x, y, width, height] on the sheet.
  scale (default 1) multiplies the drawn size.
Needs Pillow (pip install pillow).
"""
import json
import sys
from collections import defaultdict

from PIL import Image

NAMES = ['run1', 'run2', 'jump', 'duck1', 'duck2', 'cactus', 'cactus2', 'bird1', 'bird2']


def sprite_paths(img, box, scale):
    x0, y0, w, h = box
    by_color = defaultdict(list)
    for y in range(h):
        x = 0
        while x < w:
            r, g, b, a = img.getpixel((x0 + x, y0 + y))
            if a < 128:
                x += 1
                continue
            start = x
            while x < w and img.getpixel((x0 + x, y0 + y)) == (r, g, b, a):
                x += 1
            by_color['#%02x%02x%02x' % (r, g, b)].append(
                f'M{start * scale} {y * scale}h{(x - start) * scale}v{scale}h-{(x - start) * scale}z')
    return [{'fill': c, 'd': ''.join(runs)} for c, runs in by_color.items()]


def main():
    png, boxes_file, out = sys.argv[1:4]
    scale = int(sys.argv[4]) if len(sys.argv) > 4 else 1
    img = Image.open(png).convert('RGBA')
    boxes = json.load(open(boxes_file))
    missing = [n for n in NAMES if n not in boxes]
    if missing:
        sys.exit(f'boxes.json is missing: {", ".join(missing)}')
    sprites = {}
    for name in NAMES:
        _, _, w, h = boxes[name]
        sprites[name] = {'w': w * scale, 'h': h * scale, 'paths': sprite_paths(img, boxes[name], scale)}
    with open(out, 'w') as f:
        f.write('// Sprite artwork: Copyright The Chromium Authors. BSD 3-Clause; see tools/CHROMIUM-LICENSE.\n')
        f.write('// Generated by tools/sheet_to_svg.py. Each sprite is vector paths, sized in scene pixels.\n\n')
        f.write('export const SPRITES = ' + json.dumps(sprites) + ' as const\n\n')
        f.write('export type SpriteName = keyof typeof SPRITES\n')
    print(f'wrote {out}: {len(json.dumps(sprites))} characters')


if __name__ == '__main__':
    main()
