"""Turn a PNG sprite sheet into readable pixel-art sprites for dino-runner-band.

The desktop app will not draw a PNG embedded in an Svg, so hooks/sheet.ts keeps
each sprite as rows of characters, one per pixel, and turns them into SVG paths
when the plugin loads.

Usage: python3 sheet_to_svg.py sheet.png boxes.json out/sheet.ts
  boxes.json maps each sprite name to [x, y, width, height] on the sheet.
Needs Pillow (pip install pillow).
"""
import json
import sys

from PIL import Image

NAMES = ['run1', 'run2', 'jump', 'duck1', 'duck2', 'cactus', 'cactus2', 'bird1', 'bird2']

# The sheet's colors and the character each one is drawn with. Space is transparent.
PALETTE = {'#535353': '#', '#ffffff': 'o', '#f7f7f7': '-', '#fff7f7': '~'}

TEMPLATE_END = """} as const

export type SpriteName = keyof typeof ART
export type Sprite = { w: number; h: number; paths: { fill: string; d: string }[] }

// Each run of same-colored pixels in a row becomes one rectangle in that color's path.
const toSprite = (rows: readonly string[]): Sprite => {
  const runs = new Map<string, string[]>()
  rows.forEach((row, y) => {
    let x = 0
    while (x < row.length) {
      const c = row[x]
      let end = x + 1
      while (end < row.length && row[end] === c) end++
      if (c !== ' ') {
        const fill = PALETTE[c]
        runs.set(fill, [...(runs.get(fill) ?? []), `M${x} ${y}h${end - x}v1h-${end - x}z`])
      }
      x = end
    }
  })
  return { w: rows[0].length, h: rows.length, paths: [...runs].map(([fill, d]) => ({ fill, d: d.join('') })) }
}

export const SPRITES = Object.fromEntries(
  Object.entries(ART).map(([name, rows]) => [name, toSprite(rows)]),
) as Record<SpriteName, Sprite>
"""


def sprite_rows(img, box):
    x0, y0, w, h = box
    rows = []
    for y in range(h):
        row = ''
        for x in range(w):
            r, g, b, a = img.getpixel((x0 + x, y0 + y))
            if a < 128:
                row += ' '
                continue
            color = '#%02x%02x%02x' % (r, g, b)
            if color not in PALETTE:
                sys.exit(f'{color} at ({x0 + x}, {y0 + y}) is not in PALETTE')
            row += PALETTE[color]
        rows.append(row)
    return rows


def main():
    png, boxes_file, out = sys.argv[1:4]
    img = Image.open(png).convert('RGBA')
    boxes = json.load(open(boxes_file))
    missing = [n for n in NAMES if n not in boxes]
    if missing:
        sys.exit(f'boxes.json is missing: {", ".join(missing)}')
    palette = ', '.join(f"'{c}': '{color}'" if c in "#-~" else f"{c}: '{color}'" for color, c in PALETTE.items())
    lines = [
        '// Sprite artwork: Copyright The Chromium Authors. BSD 3-Clause; see tools/CHROMIUM-LICENSE.',
        '// Generated by tools/sheet_to_svg.py from the Chromium sprite sheet. One character per pixel:',
        "// PALETTE gives each character's color, and a space is transparent.",
        '',
        f'const PALETTE: Record<string, string> = {{ {palette} }}',
        '',
        'const ART = {',
    ]
    for name in NAMES:
        lines.append(f'  {name}: [')
        lines += [f"    '{row}'," for row in sprite_rows(img, boxes[name])]
        lines.append('  ],')
    with open(out, 'w') as f:
        f.write('\n'.join(lines) + '\n' + TEMPLATE_END)
    print(f'wrote {out}')


if __name__ == '__main__':
    main()
